services:
  - type: web
    name: medipredict-ai
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --workers=2 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
